version: 0.2

phases:
  install:
    commands:
      - echo "Installing Docker client"
  pre_build:
    commands:
      - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  build:
    commands:
      - docker build -t "$IMAGE_REPO:$IMAGE_TAG" .
  post_build:
    commands:
      - docker push "$IMAGE_REPO:$IMAGE_TAG"
      - echo "DONE"
