version: 0.2

env:
  parameter-store:
    DOCKERHUB_USERNAME: "/devbank/dockerhub/username"
    DOCKERHUB_TOKEN: "/devbank/dockerhub/token"

phases:
  install:
    commands:
      - echo "Install phase started: $(date)"
  pre_build:
    commands:
      - echo "Reading parameters from SSM..."
      - test -n "$DOCKERHUB_USERNAME" && echo "Got DOCKERHUB_USERNAME"
      - test -n "$DOCKERHUB_TOKEN" && echo "Got DOCKERHUB_TOKEN (length=${#DOCKERHUB_TOKEN})"
  build:
    commands:
      - echo "Build phase OK — nothing heavy for the demo."
  post_build:
    commands:
      - echo "SUCCESS: $(date)"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
