version: 0.2

env:
  parameter-store:
    DOCKERHUB_USERNAME: "/devbank/dockerhub/username"
    DOCKERHUB_TOKEN: "/devbank/dockerhub/token"

phases:
  pre_build:
    commands:
      - echo "Logging into Docker Hub..."
      - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - IMAGE="jhimanshu50/devbank-backend:latest"
  build:
    commands:
      - echo "Building image $IMAGE"
      - docker build -t "$IMAGE" .
  post_build:
    commands:
      - echo "Pushing $IMAGE"
      - docker push "$IMAGE"
      - echo "Done."
