version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "devbank-backend"
    AWS_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $DOCKERHUB_USERNAME/$IMAGE_REPO_NAME:latest .
      - echo Pushing Docker image...
      - docker push $DOCKERHUB_USERNAME/$IMAGE_REPO_NAME:latest

artifacts:
  files: '**/*'
